Library.PL/Controllers/BookController.cs
using Library.BLL.Common.Helpers.Attachments;
using Library.BLL.CustomModels.Employees;
using Library.BLL.Services.Books;
using Library.BLL.Services.Departments;
using Library.PL.Models.BookViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Library.PL.Controllers
{
    public class BookController : Controller
    {
        #region Services
        private readonly IBookServices _bookServices;
        private readonly ILogger<BookController> _logger;
        private readonly IWebHostEnvironment _environment;
        private readonly IDepartmentServices _departmentServices;
        private readonly IAttachmentSettings _attachment;

        public BookController(IBookServices bookServices,
            ILogger<BookController> logger,
            IWebHostEnvironment webHostEnvironment,
            IDepartmentServices departmentServices,
            IAttachmentSettings attachment)
        {
            _bookServices = bookServices;
            _logger = logger;
            _environment = webHostEnvironment;
            _departmentServices = departmentServices;
            _attachment = attachment;
        }
        #endregion

        #region Index
        [HttpGet]
        public async Task<IActionResult> Index(string search)
        {
            var books = await _bookServices.GetBooksAsync(search);
            return View(books);
        }
        #endregion

        #region Details
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
                return BadRequest();

            var book = await _bookServices.GetBookByIdAsync(id.Value);

            if (book is null)
                return NotFound();

            return View(book);
        }
        #endregion

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookViewModel bookVM)
        {
            var message = string.Empty;
            try
            {
                if (!ModelState.IsValid)
                    return View(bookVM);


                var createdBook = new CreateBookDto
                {
                    Title = bookVM.Title,
                    Author = bookVM.Author, 
                    DepartmentID = bookVM.DepartmentId,
                    Description = bookVM.Description,
                    PublicationYear = bookVM.PublicationYear,
                    Image = bookVM.Image,
                };

                var results = await _bookServices.CreateBookAsync(createdBook);
                if (results > 0)
                    return RedirectToAction(nameof(Index));

                message = "Book Is Not Added";
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                _logger.LogError(ex, ex.Message);

                //2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "An error has occured during adding book :(";

            }
            ModelState.AddModelError(string.Empty, message);
            return View(bookVM);
        }

        #endregion

        #region Update
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
                return BadRequest();
            var book = await _bookServices.GetBookByIdAsync(id.Value);
                
            if (book is null)
                return NotFound();

            return View(new BookViewModel()
            {
                Title = book.Title,
                Author = book.Author,
                Description = book.Description,
                PublicationYear = book.PublicationYear,
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, BookViewModel bookVM)
        {
            var message = string.Empty;

            if (!ModelState.IsValid)
                return View(bookVM);
            try
            {
                var updatedBook = new UpdateBookDto
                {
                    Id = id,
                    Title = bookVM.Title,
                    Author = bookVM.Author,
                    Description = bookVM.Description,
                    PublicationYear = bookVM.PublicationYear,
                    DepartmentID = bookVM.DepartmentId,
                    Image = bookVM.Image,
                };

                var updeted = await _bookServices.UpdateBookAsync(updatedBook) > 0;
                if (updeted)
                    return RedirectToAction(nameof(Index));

                message = "An error has occured during update book :(";
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                _logger.LogError(ex, ex.Message);

                //2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "An error has occured during updating department :(";

            }

            ModelState.AddModelError(string.Empty, message);
            return View(bookVM);
        }

        #endregion

        #region Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var message = string.Empty;

            try
            {
                var deleted = await _bookServices.DeleteBookAsync(id);
                if (deleted)
                    return RedirectToAction(nameof(Index));
                message = "An error has occured during deteting Book :(";
            }
            catch (Exception ex)
            {

                _logger.LogError(ex, ex.Message);

                //2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "An error has occured during deleting Book :(";

            }
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Library.PL/Controllers/EmployeeController.cs
using Library.BLL.Common.Helpers.Attachments;
using Library.BLL.CustomModels.Employees;
using Library.BLL.Services.Departments;
using Library.BLL.Services.Employees;
using Library.PL.Models.EmployeeViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Library.PL.Controllers
{
    public class EmployeeController : Controller
    {
        #region Services
        private readonly IEmployeeServices _employeeServices;
        private readonly ILogger<EmployeeController> _logger;
        private readonly IWebHostEnvironment _environment;
        private readonly IDepartmentServices _departmentServices;
        private readonly IAttachmentSettings _attachment;

        public EmployeeController(IEmployeeServices employeeServices,
            ILogger<EmployeeController> logger,
            IWebHostEnvironment webHostEnvironment,
            IDepartmentServices departmentServices,
            IAttachmentSettings attachment)
        {
            _employeeServices = employeeServices;
            _logger = logger;
            _environment = webHostEnvironment;
            _departmentServices = departmentServices;
            _attachment = attachment;
        }
        #endregion

        #region Index
        [HttpGet]
        public async Task<IActionResult> Index(string search)
        {
            var employees = await _employeeServices.GetEmployeesAsync(search);
            return View(employees);
        }
        #endregion
        
        #region Details
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
                return BadRequest();

            var employee = await _employeeServices.GetEmployeeByIdAsync(id.Value);

            if (employee is null)
                return NotFound();

            return View(employee);
        }
        #endregion

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {
            var message = string.Empty;
            try
            {
                if (!ModelState.IsValid)
                    return View(employeeVM);


                var createdEmployee = new CreateEmployeeDto
                {
                    Name = employeeVM.Name,
                    Address = employeeVM.Address,
                    Age = employeeVM.Age,
                    Email = employeeVM.Email,
                    Gender = employeeVM.Gender,
                    HiringDate = employeeVM.HiringDate,
                    IsActive = employeeVM.IsActive,
                    Image = employeeVM.Image,
                    PhoneNumber = employeeVM.PhoneNumber,
                    Salary = employeeVM.Salary,
                    DepartmentId = employeeVM.DepartmentId,
                };
                

                var results = await _employeeServices.CreateEmployeeAsync(createdEmployee);
                if (results > 0)
                    return RedirectToAction(nameof(Index));

                message = "Employee Is Not Added";
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                _logger.LogError(ex, ex.Message);

                //2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "An error has occured during adding employee :(";

            }
            ModelState.AddModelError(string.Empty, message);
            return View(employeeVM);
        }

        #endregion

        #region Update
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
                return BadRequest();
            var employee = await _employeeServices.GetEmployeeByIdAsync(id.Value);

            if (employee is null)
                return NotFound();

            return View(new EmployeeViewModel()
            {
                Name = employee.Name,
                Address = employee.Address,
                Email = employee.Email,
                Age = employee.Age,
                Salary = employee.Salary,
                PhoneNumber = employee.PhoneNumber,
                IsActive = employee.IsActive,
                Gender = employee.Gender,
                HiringDate = employee.HiringDate,
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, EmployeeViewModel employeeVM)
        {
            var message = string.Empty;

            if (!ModelState.IsValid)
                return View(employeeVM);
            try
            {
                var updatedEmployee = new UpdateEmployeeDto
                {
                    Id = id,
                    Name = employeeVM.Name,
                    Address = employeeVM.Address,
                    Age = employeeVM.Age,
                    Email = employeeVM.Email,
                    Gender = employeeVM.Gender,
                    HiringDate = employeeVM.HiringDate,
                    IsActive = employeeVM.IsActive,
                    PhoneNumber = employeeVM.PhoneNumber,
                    Salary = employeeVM.Salary,
                    DepartmentId = employeeVM.DepartmentId,
                    Image = employeeVM.Image,
                };

                var updeted = await _employeeServices.UpdateEmployeeAsync(updatedEmployee) > 0;
                if (updeted)
                    return RedirectToAction(nameof(Index));

                message = "An error has occured during update department :(";
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                _logger.LogError(ex, ex.Message);

                //2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "An error has occured during updating department :(";

            }

            ModelState.AddModelError(string.Empty, message);
            return View(employeeVM);
        }

        #endregion

        #region Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var message = string.Empty;

            try
            {
                var deleted = await _employeeServices.DeleteEmployeeAsync(id);
                if (deleted)
                    return RedirectToAction(nameof(Index));
                message = "An error has occured during deteting Employee :(";
            }
            catch (Exception ex)
            {

                _logger.LogError(ex, ex.Message);

                //2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "An error has occured during deleting employee :(";

            }
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Library.PL/Controllers/UserController.cs
using Library.BLL.CustomModels.Employees;
using Library.DAL.Entities.Users;
using Library.PL.Models.EmployeeViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Library.PL.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<EmployeeController> _logger;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public UserController(UserManager<ApplicationUser> userManager ,
            ILogger<EmployeeController> logger,
            IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index(string searchInp)
        {
            List<ApplicationUser> users;
            if (string.IsNullOrEmpty(searchInp))
                users = await _userManager.Users.ToListAsync();
            else
            {
                users = await _userManager.Users
                    .Where(user=>user.NormalizedEmail.Trim().Contains(searchInp.Trim().ToUpper()))
                    .ToListAsync();
            }
            return View(users);
        }
        #region Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            var message = string.Empty;

            try
            {
                var user = await _userManager.FindByIdAsync(id);

                if (user == null)
                {
                    message = "User not found.";
                }
                else
                {
                    var result = await _userManager.DeleteAsync(user);

                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        message = "An error occurred during deleting the user.";
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);

                message = _webHostEnvironment.IsDevelopment() ? ex.Message : "An error has occurred during deleting the user.";
            }
            TempData["ErrorMessage"] = message;
            return RedirectToAction(nameof(Index));
        }
        #endregion

    }
}

Library.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>@ViewData["Title"]</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/authLayout.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewData["Title"] Form</h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	@await RenderSectionAsync("validationScript", required: false)
</body>
</html>

Library.PL/Views/Shared/_ButtonsIndexPartial.cshtml
@model int
<td>
    <a  asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal-@Model">
        <i class="fas fa-trash"></i> Delete
    </button>
</td>

Library.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="header_section">
         <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                THE LIBRARY
                </a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                  </ul>
                  <form class="form-inline my-2 my-lg-0">
                     <div class="login_bt">
                        <ul>
                           <li>
                               <a class="active nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                           </li>
                        </ul>
                     </div>
                  </form>
               </div>
            </nav>
         </div>
      </div>
      <!-- header section end -->

    <div class="container">
        <main role="main" class="render pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("validationScript", required: false)
</body>
</html>